### PR TITLE
implement retina draw

### PR DESCRIPTION
**Pull request by Chilledheart**
- use QPaintDevice's device pixel radio instead of global one

- replace link-green and link-red icons

### CODE REVIEW

**Comment by Chilledheart** [comment]
Previous:
screen shot 2015-02-25 at 18 39 38
Now:
screen shot 2015-02-25 at 18 39 23

**Comment by Chilledheart** [comment]
Updated for Status Icon part:

screen shot 2015-02-25 at 18 52 33

**Comment by freeplant** [comment]
The library icon is too large. Maybe the icon is wrong?

**Comment by Chilledheart** [comment]
Yeah, these 2x icons (library icons) have the similar issue. They don't have the same margin with 1x ones.

**Comment by Chilledheart** [comment]
screen shot 2015-02-28 at 10 19 44

**Comment by lins05** [comment]
@Chilledheart please rebase this PR.

**Comment by Chilledheart** [comment]
@lins05 done

**Comment by Chilledheart** [comment]
screen shot 2015-03-02 at 13 48 48
screen shot 2015-03-02 at 13 49 08

**Pull request merged**
