### PR TITLE
Add Indonesian translation

### PR DESCRIPTION
**Pull request by atriwidada**

### CODE REVIEW

**Comment by killing** [comment]
Thank you for your contribution and sorry for the late response. Can you contribute the changes on Transifex? Just follow the instructions in the https://github.com/haiwen/seafile-client/blob/master/README.md

**Comment by atriwidada** [comment]
Hello Jiaqiang Xu,

Indonesian is there, but it seems that I have to wait for approval to
join the Indonesian team before I can do translation?

Thank you,
Andika

**Comment by atriwidada** [comment]
Translation 100% on Transifex

**Comment by killing** [comment]
Thanks a lot!

**Pull request closed without merging**
