### PR TITLE
Fix build with Qt5 v5.15.0

### PR DESCRIPTION
**Pull request by Joffr3y**

### CODE REVIEW

**Comment by yopito** [comment]
fine for me: this patch made me able to build seafile-client 7.0.8 with qt5.15.0 (VoidLinux distribution)

**Comment by yopito** [comment]
A rework might be need to support both qt 5.15 and qt < 5.15 ?

**Comment by vitlav** [comment]
> A rework might be need to support both qt 5.15 and qt < 5.15 ?
this change is backward compatible (checked with 5.12.9)

**Comment by killing** [comment]
We have added support for Qt 5.15 in the mainline. Closing this PR and thanks for the ideas!

**Pull request closed without merging**
