### PR TITLE
Show sync errors in a dialog

### PR DESCRIPTION
**Pull request by lins05**

### CODE REVIEW

**Comment by lins05** [comment]
seafile-applet_2017-01-09_09-13-53

**Comment by freeplant** [comment]
这里标题和内容应该右对齐吧

**Comment by lins05** [comment]
@freeplant 恩, 其实是左对齐的，只是第一列表头加了一个没必要的 `padding-left: 40px`, 删掉了。

screen shot 2017-01-12 at 7 22 08 pm

**Comment by killing** [comment]
Adding sync conflicts is a good idea. We'll consider about it in the next version.

**Pull request merged**
