### PR TITLE
[OSX] add sparkle support

### PR DESCRIPTION
**Pull request by Chilledheart**
[Sparkle](http://sparkle-project.org/) is a opensource software update framework (OSX).
Adding support of Sparkle will make it ease to update seafile-client by simply one-click.

This PR quite is plain but useful to kinds of our users. 

still missing:
- appcast xml generator (xml example: https://trello-attachments.s3.amazonaws.com/53e0eadf77f38b8026f922fa/551a30849583d93262bd3c26/68c0f54073d919c9506097bc80d9a1d4/GitX-dev.xml)
- upload the xml to the seafile.com website (feed url: seafile.com/appcast/stable.xml)

### CODE REVIEW

**Comment by Chilledheart** [comment]
Preview:
screen shot 2015-04-08 at 12 09 39 pm

**Comment by Chilledheart** [comment]
a simple appcast.xml is added at https://github.com/haiwen/seafile-client/pull/511/files#diff-25ca8e172bdfdd25743dcd0d085d5d88

**Comment by lins05** [comment]
LGTM.

**Comment by lins05** [comment]
Feature added in https://github.com/haiwen/seafile-client/commit/848eb03

**Pull request closed without merging**
