### PR TITLE
remove unused images

### PR DESCRIPTION
**Pull request by Chilledheart**

### CODE REVIEW

**Comment by lins05** [comment]
I'd rather have the previous python script to. Besides, we don't to need to use the external "ag" command, `git grep` is enough.

**Comment by Chilledheart** [comment]
Python is really hard to write and debug. So I prefer to golang, which has more strong static checks but still compiles fast. 

If you don't want to use the tool, ignore it simply.

**Comment by freeplant** [comment]
It is better to not introduce another language into the project. This is not a good for project maintenance.

**Comment by Chilledheart** [comment]
@freeplant Okay, but I won't tend to write python scripts any more, because I don't want to waste lots of time writing and debuging on it. Instead I will set up separate repository to keep my golang scripts.

**Pull request merged**
