### PR TITLE
Add seafile url support for OS X

### PR DESCRIPTION
**Pull request by Chilledheart**

### CODE REVIEW

**Comment by Chilledheart** [comment]
it is almost done

**Comment by vincentkersten** [comment]
After some searching I found this addition (opening the seafile folder from URL in browser (Safari in my case). 
However, giving seafile://libraryname/folder will just show the seafile applet, not open the folder. In the logs:

**Applet.log**
[02/25/16 12:48:44][FileOpen] trying to open seafile://mylibrary/Sjabloon

[02/25/16 12:48:44][OpenLocalHelper] unknown command mylibrary

---
**Seafile.log**

continous: 

[02/25/16 12:56:08] repo-mgr.c(756): Failed to access worktree /Users/vincent/Desktop/Seafile/mylibrary for repo 'mylibrary'(4d883267)

----
The library is encrypted. 

Did something change after moving to El Capitan? (I did not try this on yosimite, so don't know if this ever worked)

Hope this helps seafile forward, keep up the good work!

**Comment by lins05** [comment]
The url much be like `seafile://openfile?repo_id=<repo-id>&path=/foo`.

**Comment by vincentkersten** [comment]
Tank you for getting back to me; If I may ask for some additional info:

seafile://openfile?repo_id=mylibrary  (again from safari on osx 10.11)

**Applet.log**
[02/25/16 13:39:10][FileOpen] trying to open seafile://openfile?repo_id=mylibrary

[02/25/16 13:39:10][OpenLocalHelper] invalid repo_id mylibrary

----
The applet window is opened, but not the folder with the files. Is the repo-id the name of the library or some number/identifier? If the latter, where could i find that?
NB Adding the &path=/foo to the url gives the same result.

**Comment by lins05** [comment]
The link is not meant to be concatenated by hand. You should generate it in the cloud file browser of the client, as below:

screen shot 2016-02-25 at 9 18 47 pm


the repo id is a 36-letters-long UUID, like 16db53f9-1c6a-4c60-aa4d-4bf002c97da8. You can check the uuid of a library by right clicking on a repo in the client window, and click "view on cloud". 

In your browser you'll see the url is like `https://seafile.example.com/#my-libs/lib/16db53f9-1c6a-4c60-aa4d-4bf002c97da8`. The last part is the repo id.

**Comment by vincentkersten** [comment]
Thank you Lin for providing all this info. Works like a charm now!

**Pull request merged**
