### PR TITLE
ui: enhance event details

### PR DESCRIPTION
**Pull request by Chilledheart**

### CODE REVIEW

**Comment by Chilledheart** [comment]
it is better to use feature with #591

**Comment by Chilledheart** [comment]
screen_shot_2015-05-27_at_5 22 13_pm_720

**Comment by lins05** [comment]
When I click "open parent folder" in the context menu, the file browser shows error "failed to load", and applet.log have this:

```
[06/03/2015 09:58:18]request failed for https://cloud.seafile.com/api2/repos/b8d0c63f-6387-4661-a9f2-823a61306b9f/dir/?p=.%2F: {"error_msg": "Path does not exist"}
```

**Comment by Chilledheart** [comment]
@lins05 Sorry I forgot to rebase it against the master.

**Comment by Chilledheart** [comment]
@lins05 I think it can function well now.

**Pull request merged**
