### PR TITLE
Add sort functionality

### PR DESCRIPTION
**Pull request by Chilledheart**
include #395 , so it should rebase before being merged.

### CODE REVIEW

**Comment by lins05** [comment]
After deleting a file it becomes like this:

screen shot 2015-01-04 at 17 52 57

**Comment by lins05** [comment]
And seafile-applet crashes after selecting two files and deleting them together.

**Comment by Chilledheart** [comment]
it's a bug with deleting. should be fixed now.

**Comment by Chilledheart** [comment]
It is what the dialogs looks like on os x:

screen shot 2015-01-06 at 10 04 35

**Comment by lins05** [comment]
It still has the problem I mentioned. This is what looks like after deleting a file.

screen shot 2015-01-06 at 10 46 50

After deleting two files together:

screen shot 2015-01-06 at 10 48 39

**Comment by Chilledheart** [comment]
Sorry, but it is fine here.

**Comment by lins05** [comment]
I can reproduce the problem under both windows and mac. Can you check it on another system?

**Comment by Chilledheart** [comment]
Thanks for the lack of the details of the bug and I had to spend hours thinking about what's going wrong. So I can repeat the error by these steps:
- select some items to be deleted
- click sort indicator
- (don't deselect and) right-click these items and choose remove
 
Thanks to the qt, this bug gets fixed after using the methods such as `beginRemoveRow`. BTW I have improved the related code.

Again, nice catch for the glitching bug because it would cost me lots of debugging time if the bug left uncovered.

**Comment by Chilledheart** [comment]
I find out it still has some bugs.

**Comment by Chilledheart** [comment]
It should be fixed now.

**Pull request merged**
