### PR TITLE
[mac] sync status improvement include overlay icon support

### PR DESCRIPTION
**Pull request by Chilledheart**
- refactor code
- implement overlay icon support

### CODE REVIEW

**Comment by Chilledheart** [comment]
preview package: https://seacloud.cc/f/e86aa7d825/

SHA1SUM checksum:
e726043f0377defa2a293fcbcdf512138960ca66  seafile-client-4.2.2-overlay-icon.dmg

**Comment by Chilledheart** [comment]
preview3 package: https://seacloud.cc/f/7bd78f3e91/
SHA1SUM checksum:
227c53c6e161647c881cb9e6a4bc6bdb4dfa07d1  seafile-client-4.2.2-overlay-icon3.dmg

**Comment by lins05** [comment]
Mostly LGTM, but we should also handle "readonly" state.

**Comment by Chilledheart** [comment]
- [ ] testing on readonly status

**Comment by Chilledheart** [comment]
@lins05 support for "readonly" state has been implemented and tested

**Pull request merged**
