### PR TITLE
close all FileBrowserDialogs when we are deleting the account

### PR DESCRIPTION
**Pull request by Chilledheart**

### CODE REVIEW

**Comment by lins05** [comment]
branch name :+1: 

BTW, this PR reminds me of another issue: When I open the file browser in one account, copy an item, and switch to another account, and open a file browser again, the "copy" operation is still visible.

We should clear "files_to_be_pasted" when the user switches to another account.

**Comment by Chilledheart** [comment]
I think it is a bug with the menu. While we allow FileBrowserDialogs from different accounts exist at the same time, clearing `files_to_be_pasted` might be not so good.

**Comment by Chilledheart** [comment]
I think you mean `paste_action`.

BTW `paste_action` is visible but disabled in that case. In fact, it is intended to be visible, which tells the user that you have something in the clipboard but you are not able to paste them here.

**Comment by Chilledheart** [comment]
So I don't think it is a actual bug. It is a different tone from UI designs.

**Pull request merged**
