### PR TITLE
[win] Prefer global server configuration through HKLM

### PR DESCRIPTION
**Pull request by moobyfr**
HKCU can be used only for current logged-in user. 
HKLM will be easier because the settings will apply to all users globally, for new connected users or users which have already logged onto the workstation once

### CODE REVIEW

**Comment by moobyfr** [comment]
The documentation needs to be updated for using HKLM:
the registry entry key to use is 
 - \HK_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Seafile
for keys 
 - PreconfigureDirectory
 - PreconfigureServerAddr
 - PreconfigureServerAddrOnly

because the software is a 32bits application

**Comment by shoeper** [comment]
Not sure if this is a good idea. Seafile client settings are imho user specific.

**Comment by moobyfr** [comment]
Only preconfiguration values are stored in the HKLM tree. Other settings are stored in HKCU, which is private. Using HKLM for system-wide settings is very useful for large deployments. This will permit to deploy seafile-client on a large organisation, and prefill the server settings with an private server automatically.

**Comment by Chilledheart** [comment]
I am going to merge this and improve the algorithm by checking preconfigure settings in HKCU first and then those in HKLM.
If you have any comment or feedback, please tell us asap.

**Pull request merged**
